- id: smart_mi_fan_speed_slider_control_fan
  alias: smart_mi_fan_speed_slider_control
  trigger:
  - platform: state
    entity_id: input_slider.smart_mi_fan_speed_slider
  action:
  - service: fan.set_speed
    data_template:
      entity_id: fan.livingroomfan
      speed: '{{ trigger.to_state.state | int }}'

- id: smart_mi_fan_speed_sync_with_slider
  alias: smart_mi_fan_speed_sync_with_slider
  trigger:
  - platform: state
    entity_id: sensor.current_smart_mi_fan_speed
  action:
  - service: input_slider.select_value
    data_template:
      entity_id: input_slider.smart_mi_fan_speed_slider
      value: '{{ trigger.to_state.state }}'

- id: smart_mi_fan_shake_head_select_control_fan
  alias: smart_mi_fan_shake_head_select_control_fan
  trigger:
  - platform: state
    entity_id: input_select.smart_mi_fan_shake_head_select
  action:
  - service: fan.set_direction
    data_template:
      entity_id: fan.livingroomfan
      direction: '{{ trigger.to_state.state | int }}'

- id: smart_mi_fan_shake_head_sync_with_select
  alias: smart_mi_fan_shake_head_sync_with_select
  trigger:
  - platform: state
    entity_id: sensor.current_smart_mi_fan_shake_head_angle
  action:
  - service: input_select.select_option
    data_template:
      entity_id: input_select.smart_mi_fan_shake_head_select
      option: '{{ trigger.to_state.state }}'
