homeassistant:
  customize:
    fan.livingroomfan:
      friendly_name: 智米风扇
    input_slider.smart_mi_fan_speed_slider:
      friendly_name: 风速调节
    input_select.smart_mi_fan_shake_head_select:
      friendly_name: 摇头调节
    switch.smart_mi_fan_natural_wind_switch:
      friendly_name: 自然风开关
      icon: mdi:weather-windy

group:
  SmartMiFan:
    entities:
      - fan.livingroomfan
      - input_slider.smart_mi_fan_speed_slider
      - input_select.smart_mi_fan_shake_head_select
      - switch.smart_mi_fan_natural_wind_switch

  AllFans:
    entities:
      - fan.livingroomfan
      - input_slider.smart_mi_fan_speed_slider
      - input_select.smart_mi_fan_shake_head_select
      - switch.smart_mi_fan_natural_wind_switch

automation: !include automations.yaml

input_slider:
  smart_mi_fan_speed_slider:
    name: smart_mi_fan_speed_slider
    initial: 0
    min: 0
    max: 100
    step: 1

input_select:
  smart_mi_fan_shake_head_select:
    name: smart_mi_fan_shake_head_select
    options:
      - '0'
      - '30'
      - '60'
      - '90'
      - '120'
    initial: '0'

sensor:
  - platform: template
    sensors:
      current_smart_mi_fan_speed:
        value_template: '{{ states.fan.livingroomfan.attributes.speed_num }}'
      current_smart_mi_fan_shake_head_angle:
        value_template: '{{ states.fan.livingroomfan.attributes.angle }}'

switch:
  - platform: template
    switches:
      smart_mi_fan_natural_wind_switch:
        value_template: "{{ (states.fan.livingroomfan.state == 'on') and (states.fan.livingroomfan.attributes.natural_level != 0) }}"
        turn_on:
          service: fan.oscillate
          data:
            entity_id: fan.livingroomfan
            oscillating: true
        turn_off:
          service: fan.oscillate
          data:
            entity_id: fan.livingroomfan
            oscillating: false
fan:
  - platform: smart_mi_fan
    host: !secret fan_ip
    name: "livingroomfan"
    token: !secret fan_key
